import Sidebar from "@/components/sidebar";
import "./globals.css";
import { Inter } from "next/font/google";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dimah Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className={clsx("mx-auto bg-white w-[1000px] mt-24 flex flex-row")}
        >
          <Sidebar />
          <main className="flex flex-grow w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
